from django.conf.urls.defaults import *
urlpatterns=patterns('Video_Performance.views',
        (r'analysis?','analysis'),
        (r'summary?','summary'),
        (r'videostats2g?','videostats2g'),
        (r'videostats3g?','videostats3g'),
        (r'stats?','getStatVaritations'),
        (r'doc?','description'),
        (r'bitrateadd?','addbitrate'),
        (r'rate?','rate'),
        (r'addqoe?','addqoe'),
        (r'addstallloc?','addstallloc'),
        (r'addtcppacket?','addtcppacket'),
        (r'addphoneconf?','addphoneconf'),
        (r'regression?','regression'),
        (r'timeofday3g?','timeofday3g'),
        (r'timeofday2g?','timeofday2g'),
        (r'cdf3g?','cdf3g'),
        (r'cdf2g?','cdf2g'),
        ('','homepage'),
            )

